### ISSUE TITLE
Error when batching delta references on Git push

### ISSUE THREAD

**Issue by redrabbit** [almightycouch/gitgud#54]
Sometimes when pushing new commits to a repository, `GitRekt.WireProtocol.ReceivePack` fails to resolve some delta references:

```
Enumerating objects: 28, done.
Counting objects: 100% (28/28), done.
Delta compression using up to 8 threads
Compressing objects: 100% (19/19), done.
Writing objects: 100% (19/19), 3.97 KiB | 3.97 MiB/s, done.
Total 19 (delta 14), reused 0 (delta 0)
fatal: the remote end hung up unexpectedly
```

The backend fails with `object not found - no match for id (xxxxxxxxxxxxxxxxxxx)"`:

```
Aug 24 10:27:15 vps608629.ovh.net gitgud[6772]: 10:27:15.358 [error] GenServer #PID<0.15378.2> terminating
Aug 24 10:27:15 vps608629.ovh.net gitgud[6772]: ** (MatchError) no match of right hand side value: {:error, "object not found - no match for id (68ea65f1da68c30c530b84522240c714b5bba7ea)"}
Aug 24 10:27:15 vps608629.ovh.net gitgud[6772]: (gitrekt) lib/gitrekt/wire_protocol/receive_pack.ex:202: GitRekt.WireProtocol.ReceivePack.apply_pack_obj/3
Aug 24 10:27:15 vps608629.ovh.net gitgud[6772]: (elixir) lib/map.ex:216: Map.new_transform/3
Aug 24 10:27:15 vps608629.ovh.net gitgud[6772]: (gitrekt) lib/gitrekt/wire_protocol/receive_pack.ex:49: GitRekt.WireProtocol.ReceivePack.apply_pack/2
Aug 24 10:27:15 vps608629.ovh.net gitgud[6772]: (gitgud) lib/gitgud/repo_storage.ex:77: GitGud.RepoStorage.push/2
Aug 24 10:27:15 vps608629.ovh.net gitgud[6772]: (gitrekt) lib/gitrekt/wire_protocol/receive_pack.ex:132: GitRekt.WireProtocol.ReceivePack.next/2
```

**Comment by redrabbit** [comment]
Commit 9ebef6a seems to fix this. The Git delta reference objects need to be inserted in the right order because delta references might need a previously written delta object in order to resolve correctly. Adding a simple `Enum.reverse/2` after batching seems to do the trick.

We could also enhance things a bit by updating unresolved delta refs after each `Git.odb_write/3`. This way we could skip a few unnecessary `Git.odb_read/2` calls. I will open an other issue for this.
